### ISSUE TITLE
Choose stream option not working

### ISSUE THREAD

**Issue by razer1s** [mancuniancol/script.quasar.ruhunt-mc#1]
Start to work only after I choose English in kodi settings and restart it.(definitely it connect with addition Russian translation to quasar). Can you fix that

**Comment by mancuniancol** [comment]
Ok

**Comment by mancuniancol** [comment]
I've added a new russian translation file. I hope that fix the problem. Please, let me know if it works for you

**Comment by razer1s** [comment]
OK. It was problem with previews version of quasar, not your provider, but I'll check
