### ISSUE TITLE
default language for seach  

### ISSUE THREAD

**Issue by razer1s** [mancuniancol/script.quasar.ruhunt-mc#3]
change please default language for seach to russian, becouse almost all russian films that have titles in russian don't seaching

**Comment by mancuniancol** [comment]
OK, I didn't have too much time to check this. Could you share your debug log with pastebin.com to do some test this weekend?

**Comment by razer1s** [comment]
as i understand you must only change "en" to "ru" in all strings where this need in main.py

**Comment by mancuniancol** [comment]
Yes, because it is being a lot of changes lately. Usually, I do a big copy/paste and I fix the regressions for it.  I've released version 1.3.1 fixing the problem for movies.  I am not sure about series or seasons.

**Comment by mancuniancol** [comment]
https://github.com/mancuniancol/script.quasar.ruhunt-mc/archive/v1.3.1.zip

**Comment by razer1s** [comment]
All works (serials too) as i wanted. thanks

**Comment by mancuniancol** [comment]
Thanks for your feedback. I don't have time to test all the providers and I relay from the users to improve or fix them. Specially, providers not English language :)
